FROM node:20

RUN apt-get update \ 
    && apt-get upgrade -y \
    && apt-get install -y ranger vim

WORKDIR /home/node/app
RUN corepack enable

COPY .yarnrc.yml .
COPY package.json .
COPY yarn.lock .

RUN chown -R node:node .
USER node

RUN yarn install --immutable
COPY --chown=node:node . .
