# IMAGE FOR BUILDING
FROM cokoapps/base:24

WORKDIR /home/node/app
RUN corepack enable

COPY .yarnrc.yml .
COPY package.json .
COPY yarn.lock .

RUN yarn install --immutable

COPY ./dev/client ./dev/client
COPY ./scripts/coko-client-build.mjs ./scripts/coko-client-build.mjs
COPY ./src ./src
COPY ./vite ./vite

ENV NODE_ENV='production'
ENV CLIENT_PAGE_TITLE='Coko client playground'
ENV CLIENT_FAVICON_PATH='../static/favicon.ico'
ENV CLIENT_LANGUAGE='en-US'
ENV CLIENT_APP_ROOT_PATH='./dev/client/app'

RUN node ./scripts/coko-client-build.mjs

######################################################################
######################################################################

# IMAGE FOR RUNNING

FROM node:24-bookworm-slim

RUN apt-get update && apt-get install -y
RUN npm install --global serve

WORKDIR /home/node/app

COPY --from=0 /home/node/app/dev/client/_build ./_build
COPY ./scripts/env.sh ./env.sh

RUN chown -R node:node .
USER node
