FROM node:20-bookworm-slim

RUN apt-get update \
    && apt-get upgrade -y \
    && apt-get install -y ranger vim

WORKDIR /home/node/client
RUN corepack enable

COPY package.json .
COPY yarn.lock .

RUN chown -R node:node .
USER node

RUN yarn install --immutable

COPY --chown=node:node . .
