#!/bin/sh

rm -f ./_build/env.js
touch ./_build/env.js

# remove double or single quotes around values, if any
SERVER_URL=${SERVER_URL#\"}
SERVER_URL=${SERVER_URL%\"}
SERVER_URL=${SERVER_URL#\'}
SERVER_URL=${SERVER_URL%\'}

WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\"}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL#\'}
WEBSOCKET_SERVER_URL=${WEBSOCKET_SERVER_URL%\'}

YJS_WEBSOCKET_SERVER_URL=${YJS_WEBSOCKET_SERVER_URL#\"}
YJS_WEBSOCKET_SERVER_URL=${YJS_WEBSOCKET_SERVER_URL%\"}
YJS_WEBSOCKET_SERVER_URL=${YJS_WEBSOCKET_SERVER_URL#\'}
YJS_WEBSOCKET_SERVER_URL=${YJS_WEBSOCKET_SERVER_URL%\'}

SENTRY_DSN=${SENTRY_DSN#\"}
SENTRY_DSN=${SENTRY_DSN%\"}
SENTRY_DSN=${SENTRY_DSN#\'}
SENTRY_DSN=${SENTRY_DSN%\'}

SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT#\"}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT%\"}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT#\'}
SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT%\'}

cat <<EOF > _build/env.js
window.env = {
    serverUrl: '${SERVER_URL}',
    websocketServerUrl: '${WEBSOCKET_SERVER_URL}',
    yjsWebsocketServerUrl: '${YJS_WEBSOCKET_SERVER_URL}',
    sentry: { dsn: '${SENTRY_DSN}', environment: '${SENTRY_ENVIRONMENT}' },
}
EOF

exec "$@"
